services:
  app:
    build: .
    container_name: payment_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
      gateway:
        condition: service_started
    command: >
      sh -c "[ -d vendor ] || composer install --no-interaction --prefer-dist --no-progress &&
             php artisan migrate --force &&
             php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: payment_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  gateway:
    image: matheusprotzen/gateways-mock
    container_name: gateway
    restart: unless-stopped
    ports:
      - "3001:3001"
      - "3002:3002"

volumes:
  db_data:
